### ISSUE TITLE
Heroku API Key and Forking

### ISSUE THREAD

**Issue by idkjs** [CircleCI-Public/circleci-demo-python-flask#1]
TL;DR: Make a note to walkthrough users that they will have to add their [Heroku API Key](https://dashboard.heroku.com/account) to CircleCI before starting or the first error wont look like the walkthrough. You will get this:

```bash
if [ "${CIRCLE_BRANCH}" == "master" ]; then
  git push heroku master
  heroku run python manage.py deploy
  heroku restart
fi
Shell: /bin/bash -eo pipefail

Username for 'https://git.heroku.com': fatal: could not read Username for 'https://git.heroku.com': No such file or directory
Exited with code 128

```
Adding the key will get you the expected first error.

Also: When forking, make sure to change project name to not conflict on Heroku with the tutorial instance which has the 'cci-demo-walkthrough' namespace occupied.

**Comment by keybits** [comment]
Thanks for the feedback - I'll be adding this to the README and tutorial soon.

**Comment by keybits** [comment]
Fixed with: https://github.com/circleci/circleci-docs/pull/1506
