### ISSUE TITLE
sample config.yml job

### ISSUE THREAD

**Issue by idkjs** [CircleCI-Public/circleci-demo-python-flask#2]
In the [job section](https://circleci.com/docs/2.0/project-walkthrough/?utm_source=autoemail&utm_medium=email&utm_campaign=2.0signup#add-a-job) of walkthrough, consider changing the working_directory from ~/circulate to ~/<project-root>. For noobs, this is not evident since 'circulate' is not the name of the demo project.

In config.yml:
```bash
version: 2
jobs:
  build:
    working_directory: ~/<project-root>
    docker:
      - image: python:3.6.0
    steps:
      - checkout
      - run: echo "hello world"
```

**Comment by keybits** [comment]
Thanks for the feedback. I've now removed `working_directory` since it's not require any more.
