### ISSUE TITLE
Tests in parallel

### ISSUE THREAD

**Issue by zzak** [CircleCI-Public/circleci-demo-python-flask#5]
Hey @keybits,

Are the tests running in parallel, or can we set them up to?

:bow:

**Comment by keybits** [comment]
On the todo list :-) Ideally I'd like to configure a separate branch with lots of test to demonstrate parallelism on 2.0.

**Comment by keybits** [comment]
Added as a TODO in https://github.com/CircleCI-Public/circleci-demo-python-flask/blob/master/README.md
